<!--link rel="stylesheet" href="<?php echo base_url();?>assets/template/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo base_url();?>assets/template/font-awesome/css/font-awesome.min.css"--> 
<style type="text/css">
	.sel_ico:hover{
		/*font-size: 110%;*/
		background: silver;
	}
	.sel_ico:active{
		/*font-size: 110%;*/
		background: #3c8dbc;
	}
</style>

<script type="text/javascript">
	$(".sel_ico").on("click", function(){
		var sel_ico = $(this).attr("value");
		$("#icono").val(sel_ico);
	});
</script>

<div class="row">
	<div class="col-md-1 sel_ico" value="fa-glass"><i class="fa fa-2x fa-glass"></i></div>
<div class="col-md-1 sel_ico" value="fa-music"><i class="fa fa-2x fa-music"></i></div>
<div class="col-md-1 sel_ico" value="fa-search"><i class="fa fa-2x fa-search"></i></div>
<div class="col-md-1 sel_ico" value="fa-envelope-o"><i class="fa fa-2x fa-envelope-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-heart"><i class="fa fa-2x fa-heart"></i></div>
<div class="col-md-1 sel_ico" value="fa-star"><i class="fa fa-2x fa-star"></i></div>
<div class="col-md-1 sel_ico" value="fa-star-o"><i class="fa fa-2x fa-star-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-user"><i class="fa fa-2x fa-user"></i></div>
<div class="col-md-1 sel_ico" value="fa-film"><i class="fa fa-2x fa-film"></i></div>
<div class="col-md-1 sel_ico" value="fa-th-large"><i class="fa fa-2x fa-th-large"></i></div>
<div class="col-md-1 sel_ico" value="fa-th"><i class="fa fa-2x fa-th"></i></div>
<div class="col-md-1 sel_ico" value="fa-th-list"><i class="fa fa-2x fa-th-list"></i></div>
<div class="col-md-1 sel_ico" value="fa-check"><i class="fa fa-2x fa-check"></i></div>
<div class="col-md-1 sel_ico" value="fa-remove"><i class="fa fa-2x fa-remove"></i></div>
<div class="col-md-1 sel_ico" value="fa-close"><i class="fa fa-2x fa-close"></i></div>
<div class="col-md-1 sel_ico" value="fa-times"><i class="fa fa-2x fa-times"></i></div>
<div class="col-md-1 sel_ico" value="fa-search-plus"><i class="fa fa-2x fa-search-plus"></i></div>
<div class="col-md-1 sel_ico" value="fa-search-minus"><i class="fa fa-2x fa-search-minus"></i></div>
<div class="col-md-1 sel_ico" value="fa-power-off"><i class="fa fa-2x fa-power-off"></i></div>
<div class="col-md-1 sel_ico" value="fa-signal"><i class="fa fa-2x fa-signal"></i></div>
<div class="col-md-1 sel_ico" value="fa-gear"><i class="fa fa-2x fa-gear"></i></div>
<div class="col-md-1 sel_ico" value="fa-cog"><i class="fa fa-2x fa-cog"></i></div>
<div class="col-md-1 sel_ico" value="fa-trash-o"><i class="fa fa-2x fa-trash-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-home"><i class="fa fa-2x fa-home"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-o"><i class="fa fa-2x fa-file-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-clock-o"><i class="fa fa-2x fa-clock-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-road"><i class="fa fa-2x fa-road"></i></div>
<div class="col-md-1 sel_ico" value="fa-download"><i class="fa fa-2x fa-download"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-o-down"><i class="fa fa-2x fa-arrow-circle-o-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-o-up"><i class="fa fa-2x fa-arrow-circle-o-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-inbox"><i class="fa fa-2x fa-inbox"></i></div>
<div class="col-md-1 sel_ico" value="fa-play-circle-o"><i class="fa fa-2x fa-play-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-rotate-right"><i class="fa fa-2x fa-rotate-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-repeat"><i class="fa fa-2x fa-repeat"></i></div>
<div class="col-md-1 sel_ico" value="fa-refresh"><i class="fa fa-2x fa-refresh"></i></div>
<div class="col-md-1 sel_ico" value="fa-list-alt"><i class="fa fa-2x fa-list-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-lock"><i class="fa fa-2x fa-lock"></i></div>
<div class="col-md-1 sel_ico" value="fa-flag"><i class="fa fa-2x fa-flag"></i></div>
<div class="col-md-1 sel_ico" value="fa-headphones"><i class="fa fa-2x fa-headphones"></i></div>
<div class="col-md-1 sel_ico" value="fa-volume-off"><i class="fa fa-2x fa-volume-off"></i></div>
<div class="col-md-1 sel_ico" value="fa-volume-down"><i class="fa fa-2x fa-volume-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-volume-up"><i class="fa fa-2x fa-volume-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-qrcode"><i class="fa fa-2x fa-qrcode"></i></div>
<div class="col-md-1 sel_ico" value="fa-barcode"><i class="fa fa-2x fa-barcode"></i></div>
<div class="col-md-1 sel_ico" value="fa-tag"><i class="fa fa-2x fa-tag"></i></div>
<div class="col-md-1 sel_ico" value="fa-tags"><i class="fa fa-2x fa-tags"></i></div>
<div class="col-md-1 sel_ico" value="fa-book"><i class="fa fa-2x fa-book"></i></div>
<div class="col-md-1 sel_ico" value="fa-bookmark"><i class="fa fa-2x fa-bookmark"></i></div>
<div class="col-md-1 sel_ico" value="fa-print"><i class="fa fa-2x fa-print"></i></div>
<div class="col-md-1 sel_ico" value="fa-camera"><i class="fa fa-2x fa-camera"></i></div>
<div class="col-md-1 sel_ico" value="fa-font"><i class="fa fa-2x fa-font"></i></div>
<div class="col-md-1 sel_ico" value="fa-bold"><i class="fa fa-2x fa-bold"></i></div>
<div class="col-md-1 sel_ico" value="fa-italic"><i class="fa fa-2x fa-italic"></i></div>
<div class="col-md-1 sel_ico" value="fa-text-height"><i class="fa fa-2x fa-text-height"></i></div>
<div class="col-md-1 sel_ico" value="fa-text-width"><i class="fa fa-2x fa-text-width"></i></div>
<div class="col-md-1 sel_ico" value="fa-align-left"><i class="fa fa-2x fa-align-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-align-center"><i class="fa fa-2x fa-align-center"></i></div>
<div class="col-md-1 sel_ico" value="fa-align-right"><i class="fa fa-2x fa-align-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-align-justify"><i class="fa fa-2x fa-align-justify"></i></div>
<div class="col-md-1 sel_ico" value="fa-list"><i class="fa fa-2x fa-list"></i></div>
<div class="col-md-1 sel_ico" value="fa-dedent"><i class="fa fa-2x fa-dedent"></i></div>
<div class="col-md-1 sel_ico" value="fa-outdent"><i class="fa fa-2x fa-outdent"></i></div>
<div class="col-md-1 sel_ico" value="fa-indent"><i class="fa fa-2x fa-indent"></i></div>
<div class="col-md-1 sel_ico" value="fa-video-camera"><i class="fa fa-2x fa-video-camera"></i></div>
<div class="col-md-1 sel_ico" value="fa-photo"><i class="fa fa-2x fa-photo"></i></div>
<div class="col-md-1 sel_ico" value="fa-image"><i class="fa fa-2x fa-image"></i></div>
<div class="col-md-1 sel_ico" value="fa-picture-o"><i class="fa fa-2x fa-picture-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-pencil"><i class="fa fa-2x fa-pencil"></i></div>
<div class="col-md-1 sel_ico" value="fa-map-marker"><i class="fa fa-2x fa-map-marker"></i></div>
<div class="col-md-1 sel_ico" value="fa-adjust"><i class="fa fa-2x fa-adjust"></i></div>
<div class="col-md-1 sel_ico" value="fa-tint"><i class="fa fa-2x fa-tint"></i></div>
<div class="col-md-1 sel_ico" value="fa-edit"><i class="fa fa-2x fa-edit"></i></div>
<div class="col-md-1 sel_ico" value="fa-pencil-square-o"><i class="fa fa-2x fa-pencil-square-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-share-square-o"><i class="fa fa-2x fa-share-square-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-check-square-o"><i class="fa fa-2x fa-check-square-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrows"><i class="fa fa-2x fa-arrows"></i></div>
<div class="col-md-1 sel_ico" value="fa-step-backward"><i class="fa fa-2x fa-step-backward"></i></div>
<div class="col-md-1 sel_ico" value="fa-fast-backward"><i class="fa fa-2x fa-fast-backward"></i></div>
<div class="col-md-1 sel_ico" value="fa-backward"><i class="fa fa-2x fa-backward"></i></div>
<div class="col-md-1 sel_ico" value="fa-play"><i class="fa fa-2x fa-play"></i></div>
<div class="col-md-1 sel_ico" value="fa-pause"><i class="fa fa-2x fa-pause"></i></div>
<div class="col-md-1 sel_ico" value="fa-stop"><i class="fa fa-2x fa-stop"></i></div>
<div class="col-md-1 sel_ico" value="fa-forward"><i class="fa fa-2x fa-forward"></i></div>
<div class="col-md-1 sel_ico" value="fa-fast-forward"><i class="fa fa-2x fa-fast-forward"></i></div>
<div class="col-md-1 sel_ico" value="fa-step-forward"><i class="fa fa-2x fa-step-forward"></i></div>
<div class="col-md-1 sel_ico" value="fa-eject"><i class="fa fa-2x fa-eject"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-left"><i class="fa fa-2x fa-chevron-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-right"><i class="fa fa-2x fa-chevron-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-plus-circle"><i class="fa fa-2x fa-plus-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-minus-circle"><i class="fa fa-2x fa-minus-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-times-circle"><i class="fa fa-2x fa-times-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-check-circle"><i class="fa fa-2x fa-check-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-question-circle"><i class="fa fa-2x fa-question-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-info-circle"><i class="fa fa-2x fa-info-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-crosshairs"><i class="fa fa-2x fa-crosshairs"></i></div>
<div class="col-md-1 sel_ico" value="fa-times-circle-o"><i class="fa fa-2x fa-times-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-check-circle-o"><i class="fa fa-2x fa-check-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-ban"><i class="fa fa-2x fa-ban"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-left"><i class="fa fa-2x fa-arrow-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-right"><i class="fa fa-2x fa-arrow-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-up"><i class="fa fa-2x fa-arrow-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-down"><i class="fa fa-2x fa-arrow-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-mail-forward"><i class="fa fa-2x fa-mail-forward"></i></div>
<div class="col-md-1 sel_ico" value="fa-share"><i class="fa fa-2x fa-share"></i></div>
<div class="col-md-1 sel_ico" value="fa-expand"><i class="fa fa-2x fa-expand"></i></div>
<div class="col-md-1 sel_ico" value="fa-compress"><i class="fa fa-2x fa-compress"></i></div>
<div class="col-md-1 sel_ico" value="fa-plus"><i class="fa fa-2x fa-plus"></i></div>
<div class="col-md-1 sel_ico" value="fa-minus"><i class="fa fa-2x fa-minus"></i></div>
<div class="col-md-1 sel_ico" value="fa-asterisk"><i class="fa fa-2x fa-asterisk"></i></div>
<div class="col-md-1 sel_ico" value="fa-exclamation-circle"><i class="fa fa-2x fa-exclamation-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-gift"><i class="fa fa-2x fa-gift"></i></div>
<div class="col-md-1 sel_ico" value="fa-leaf"><i class="fa fa-2x fa-leaf"></i></div>
<div class="col-md-1 sel_ico" value="fa-fire"><i class="fa fa-2x fa-fire"></i></div>
<div class="col-md-1 sel_ico" value="fa-eye"><i class="fa fa-2x fa-eye"></i></div>
<div class="col-md-1 sel_ico" value="fa-eye-slash"><i class="fa fa-2x fa-eye-slash"></i></div>
<div class="col-md-1 sel_ico" value="fa-warning"><i class="fa fa-2x fa-warning"></i></div>
<div class="col-md-1 sel_ico" value="fa-exclamation-triangle"><i class="fa fa-2x fa-exclamation-triangle"></i></div>
<div class="col-md-1 sel_ico" value="fa-plane"><i class="fa fa-2x fa-plane"></i></div>
<div class="col-md-1 sel_ico" value="fa-calendar"><i class="fa fa-2x fa-calendar"></i></div>
<div class="col-md-1 sel_ico" value="fa-random"><i class="fa fa-2x fa-random"></i></div>
<div class="col-md-1 sel_ico" value="fa-comment"><i class="fa fa-2x fa-comment"></i></div>
<div class="col-md-1 sel_ico" value="fa-magnet"><i class="fa fa-2x fa-magnet"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-up"><i class="fa fa-2x fa-chevron-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-down"><i class="fa fa-2x fa-chevron-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-retweet"><i class="fa fa-2x fa-retweet"></i></div>
<div class="col-md-1 sel_ico" value="fa-shopping-cart"><i class="fa fa-2x fa-shopping-cart"></i></div>
<div class="col-md-1 sel_ico" value="fa-folder"><i class="fa fa-2x fa-folder"></i></div>
<div class="col-md-1 sel_ico" value="fa-folder-open"><i class="fa fa-2x fa-folder-open"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrows-v"><i class="fa fa-2x fa-arrows-v"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrows-h"><i class="fa fa-2x fa-arrows-h"></i></div>
<div class="col-md-1 sel_ico" value="fa-bar-chart-o"><i class="fa fa-2x fa-bar-chart-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-bar-chart"><i class="fa fa-2x fa-bar-chart"></i></div>
<div class="col-md-1 sel_ico" value="fa-twitter-square"><i class="fa fa-2x fa-twitter-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-facebook-square"><i class="fa fa-2x fa-facebook-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-camera-retro"><i class="fa fa-2x fa-camera-retro"></i></div>
<div class="col-md-1 sel_ico" value="fa-key"><i class="fa fa-2x fa-key"></i></div>
<div class="col-md-1 sel_ico" value="fa-gears"><i class="fa fa-2x fa-gears"></i></div>
<div class="col-md-1 sel_ico" value="fa-cogs"><i class="fa fa-2x fa-cogs"></i></div>
<div class="col-md-1 sel_ico" value="fa-comments"><i class="fa fa-2x fa-comments"></i></div>
<div class="col-md-1 sel_ico" value="fa-thumbs-o-up"><i class="fa fa-2x fa-thumbs-o-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-thumbs-o-down"><i class="fa fa-2x fa-thumbs-o-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-star-half"><i class="fa fa-2x fa-star-half"></i></div>
<div class="col-md-1 sel_ico" value="fa-heart-o"><i class="fa fa-2x fa-heart-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-sign-out"><i class="fa fa-2x fa-sign-out"></i></div>
<div class="col-md-1 sel_ico" value="fa-linkedin-square"><i class="fa fa-2x fa-linkedin-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-thumb-tack"><i class="fa fa-2x fa-thumb-tack"></i></div>
<div class="col-md-1 sel_ico" value="fa-external-link"><i class="fa fa-2x fa-external-link"></i></div>
<div class="col-md-1 sel_ico" value="fa-sign-in"><i class="fa fa-2x fa-sign-in"></i></div>
<div class="col-md-1 sel_ico" value="fa-trophy"><i class="fa fa-2x fa-trophy"></i></div>
<div class="col-md-1 sel_ico" value="fa-github-square"><i class="fa fa-2x fa-github-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-upload"><i class="fa fa-2x fa-upload"></i></div>
<div class="col-md-1 sel_ico" value="fa-lemon-o"><i class="fa fa-2x fa-lemon-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-phone"><i class="fa fa-2x fa-phone"></i></div>
<div class="col-md-1 sel_ico" value="fa-square-o"><i class="fa fa-2x fa-square-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-bookmark-o"><i class="fa fa-2x fa-bookmark-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-phone-square"><i class="fa fa-2x fa-phone-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-twitter"><i class="fa fa-2x fa-twitter"></i></div>
<div class="col-md-1 sel_ico" value="fa-facebook-f"><i class="fa fa-2x fa-facebook-f"></i></div>
<div class="col-md-1 sel_ico" value="fa-facebook"><i class="fa fa-2x fa-facebook"></i></div>
<div class="col-md-1 sel_ico" value="fa-github"><i class="fa fa-2x fa-github"></i></div>
<div class="col-md-1 sel_ico" value="fa-unlock"><i class="fa fa-2x fa-unlock"></i></div>
<div class="col-md-1 sel_ico" value="fa-credit-card"><i class="fa fa-2x fa-credit-card"></i></div>
<div class="col-md-1 sel_ico" value="fa-feed"><i class="fa fa-2x fa-feed"></i></div>
<div class="col-md-1 sel_ico" value="fa-rss"><i class="fa fa-2x fa-rss"></i></div>
<div class="col-md-1 sel_ico" value="fa-hdd-o"><i class="fa fa-2x fa-hdd-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-bullhorn"><i class="fa fa-2x fa-bullhorn"></i></div>
<div class="col-md-1 sel_ico" value="fa-bell"><i class="fa fa-2x fa-bell"></i></div>
<div class="col-md-1 sel_ico" value="fa-certificate"><i class="fa fa-2x fa-certificate"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-o-right"><i class="fa fa-2x fa-hand-o-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-o-left"><i class="fa fa-2x fa-hand-o-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-o-up"><i class="fa fa-2x fa-hand-o-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-o-down"><i class="fa fa-2x fa-hand-o-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-left"><i class="fa fa-2x fa-arrow-circle-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-right"><i class="fa fa-2x fa-arrow-circle-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-up"><i class="fa fa-2x fa-arrow-circle-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-down"><i class="fa fa-2x fa-arrow-circle-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-globe"><i class="fa fa-2x fa-globe"></i></div>
<div class="col-md-1 sel_ico" value="fa-wrench"><i class="fa fa-2x fa-wrench"></i></div>
<div class="col-md-1 sel_ico" value="fa-tasks"><i class="fa fa-2x fa-tasks"></i></div>
<div class="col-md-1 sel_ico" value="fa-filter"><i class="fa fa-2x fa-filter"></i></div>
<div class="col-md-1 sel_ico" value="fa-briefcase"><i class="fa fa-2x fa-briefcase"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrows-alt"><i class="fa fa-2x fa-arrows-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-group"><i class="fa fa-2x fa-group"></i></div>
<div class="col-md-1 sel_ico" value="fa-users"><i class="fa fa-2x fa-users"></i></div>
<div class="col-md-1 sel_ico" value="fa-chain"><i class="fa fa-2x fa-chain"></i></div>
<div class="col-md-1 sel_ico" value="fa-link"><i class="fa fa-2x fa-link"></i></div>
<div class="col-md-1 sel_ico" value="fa-cloud"><i class="fa fa-2x fa-cloud"></i></div>
<div class="col-md-1 sel_ico" value="fa-flask"><i class="fa fa-2x fa-flask"></i></div>
<div class="col-md-1 sel_ico" value="fa-cut"><i class="fa fa-2x fa-cut"></i></div>
<div class="col-md-1 sel_ico" value="fa-scissors"><i class="fa fa-2x fa-scissors"></i></div>
<div class="col-md-1 sel_ico" value="fa-copy"><i class="fa fa-2x fa-copy"></i></div>
<div class="col-md-1 sel_ico" value="fa-files-o"><i class="fa fa-2x fa-files-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-paperclip"><i class="fa fa-2x fa-paperclip"></i></div>
<div class="col-md-1 sel_ico" value="fa-save"><i class="fa fa-2x fa-save"></i></div>
<div class="col-md-1 sel_ico" value="fa-floppy-o"><i class="fa fa-2x fa-floppy-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-square"><i class="fa fa-2x fa-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-navicon"><i class="fa fa-2x fa-navicon"></i></div>
<div class="col-md-1 sel_ico" value="fa-reorder"><i class="fa fa-2x fa-reorder"></i></div>
<div class="col-md-1 sel_ico" value="fa-bars"><i class="fa fa-2x fa-bars"></i></div>
<div class="col-md-1 sel_ico" value="fa-list-ul"><i class="fa fa-2x fa-list-ul"></i></div>
<div class="col-md-1 sel_ico" value="fa-list-ol"><i class="fa fa-2x fa-list-ol"></i></div>
<div class="col-md-1 sel_ico" value="fa-strikethrough"><i class="fa fa-2x fa-strikethrough"></i></div>
<div class="col-md-1 sel_ico" value="fa-underline"><i class="fa fa-2x fa-underline"></i></div>
<div class="col-md-1 sel_ico" value="fa-table"><i class="fa fa-2x fa-table"></i></div>
<div class="col-md-1 sel_ico" value="fa-magic"><i class="fa fa-2x fa-magic"></i></div>
<div class="col-md-1 sel_ico" value="fa-truck"><i class="fa fa-2x fa-truck"></i></div>
<div class="col-md-1 sel_ico" value="fa-pinterest"><i class="fa fa-2x fa-pinterest"></i></div>
<div class="col-md-1 sel_ico" value="fa-pinterest-square"><i class="fa fa-2x fa-pinterest-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-google-plus-square"><i class="fa fa-2x fa-google-plus-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-google-plus"><i class="fa fa-2x fa-google-plus"></i></div>
<div class="col-md-1 sel_ico" value="fa-money"><i class="fa fa-2x fa-money"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-down"><i class="fa fa-2x fa-caret-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-up"><i class="fa fa-2x fa-caret-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-left"><i class="fa fa-2x fa-caret-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-right"><i class="fa fa-2x fa-caret-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-columns"><i class="fa fa-2x fa-columns"></i></div>
<div class="col-md-1 sel_ico" value="fa-unsorted"><i class="fa fa-2x fa-unsorted"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort"><i class="fa fa-2x fa-sort"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-down"><i class="fa fa-2x fa-sort-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-desc"><i class="fa fa-2x fa-sort-desc"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-up"><i class="fa fa-2x fa-sort-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-asc"><i class="fa fa-2x fa-sort-asc"></i></div>
<div class="col-md-1 sel_ico" value="fa-envelope"><i class="fa fa-2x fa-envelope"></i></div>
<div class="col-md-1 sel_ico" value="fa-linkedin"><i class="fa fa-2x fa-linkedin"></i></div>
<div class="col-md-1 sel_ico" value="fa-rotate-left"><i class="fa fa-2x fa-rotate-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-undo"><i class="fa fa-2x fa-undo"></i></div>
<div class="col-md-1 sel_ico" value="fa-legal"><i class="fa fa-2x fa-legal"></i></div>
<div class="col-md-1 sel_ico" value="fa-gavel"><i class="fa fa-2x fa-gavel"></i></div>
<div class="col-md-1 sel_ico" value="fa-dashboard"><i class="fa fa-2x fa-dashboard"></i></div>
<div class="col-md-1 sel_ico" value="fa-tachometer"><i class="fa fa-2x fa-tachometer"></i></div>
<div class="col-md-1 sel_ico" value="fa-comment-o"><i class="fa fa-2x fa-comment-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-comments-o"><i class="fa fa-2x fa-comments-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-flash"><i class="fa fa-2x fa-flash"></i></div>
<div class="col-md-1 sel_ico" value="fa-bolt"><i class="fa fa-2x fa-bolt"></i></div>
<div class="col-md-1 sel_ico" value="fa-sitemap"><i class="fa fa-2x fa-sitemap"></i></div>
<div class="col-md-1 sel_ico" value="fa-umbrella"><i class="fa fa-2x fa-umbrella"></i></div>
<div class="col-md-1 sel_ico" value="fa-paste"><i class="fa fa-2x fa-paste"></i></div>
<div class="col-md-1 sel_ico" value="fa-clipboard"><i class="fa fa-2x fa-clipboard"></i></div>
<div class="col-md-1 sel_ico" value="fa-lightbulb-o"><i class="fa fa-2x fa-lightbulb-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-exchange"><i class="fa fa-2x fa-exchange"></i></div>
<div class="col-md-1 sel_ico" value="fa-cloud-download"><i class="fa fa-2x fa-cloud-download"></i></div>
<div class="col-md-1 sel_ico" value="fa-cloud-upload"><i class="fa fa-2x fa-cloud-upload"></i></div>
<div class="col-md-1 sel_ico" value="fa-user-md"><i class="fa fa-2x fa-user-md"></i></div>
<div class="col-md-1 sel_ico" value="fa-stethoscope"><i class="fa fa-2x fa-stethoscope"></i></div>
<div class="col-md-1 sel_ico" value="fa-suitcase"><i class="fa fa-2x fa-suitcase"></i></div>
<div class="col-md-1 sel_ico" value="fa-bell-o"><i class="fa fa-2x fa-bell-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-coffee"><i class="fa fa-2x fa-coffee"></i></div>
<div class="col-md-1 sel_ico" value="fa-cutlery"><i class="fa fa-2x fa-cutlery"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-text-o"><i class="fa fa-2x fa-file-text-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-building-o"><i class="fa fa-2x fa-building-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hospital-o"><i class="fa fa-2x fa-hospital-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-ambulance"><i class="fa fa-2x fa-ambulance"></i></div>
<div class="col-md-1 sel_ico" value="fa-medkit"><i class="fa fa-2x fa-medkit"></i></div>
<div class="col-md-1 sel_ico" value="fa-fighter-jet"><i class="fa fa-2x fa-fighter-jet"></i></div>
<div class="col-md-1 sel_ico" value="fa-beer"><i class="fa fa-2x fa-beer"></i></div>
<div class="col-md-1 sel_ico" value="fa-h-square"><i class="fa fa-2x fa-h-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-plus-square"><i class="fa fa-2x fa-plus-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-double-left"><i class="fa fa-2x fa-angle-double-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-double-right"><i class="fa fa-2x fa-angle-double-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-double-up"><i class="fa fa-2x fa-angle-double-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-double-down"><i class="fa fa-2x fa-angle-double-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-left"><i class="fa fa-2x fa-angle-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-right"><i class="fa fa-2x fa-angle-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-up"><i class="fa fa-2x fa-angle-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-angle-down"><i class="fa fa-2x fa-angle-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-desktop"><i class="fa fa-2x fa-desktop"></i></div>
<div class="col-md-1 sel_ico" value="fa-laptop"><i class="fa fa-2x fa-laptop"></i></div>
<div class="col-md-1 sel_ico" value="fa-tablet"><i class="fa fa-2x fa-tablet"></i></div>
<div class="col-md-1 sel_ico" value="fa-mobile-phone"><i class="fa fa-2x fa-mobile-phone"></i></div>
<div class="col-md-1 sel_ico" value="fa-mobile"><i class="fa fa-2x fa-mobile"></i></div>
<div class="col-md-1 sel_ico" value="fa-circle-o"><i class="fa fa-2x fa-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-quote-left"><i class="fa fa-2x fa-quote-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-quote-right"><i class="fa fa-2x fa-quote-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-spinner"><i class="fa fa-2x fa-spinner"></i></div>
<div class="col-md-1 sel_ico" value="fa-circle"><i class="fa fa-2x fa-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-mail-reply"><i class="fa fa-2x fa-mail-reply"></i></div>
<div class="col-md-1 sel_ico" value="fa-reply"><i class="fa fa-2x fa-reply"></i></div>
<div class="col-md-1 sel_ico" value="fa-github-alt"><i class="fa fa-2x fa-github-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-folder-o"><i class="fa fa-2x fa-folder-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-folder-open-o"><i class="fa fa-2x fa-folder-open-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-smile-o"><i class="fa fa-2x fa-smile-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-frown-o"><i class="fa fa-2x fa-frown-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-meh-o"><i class="fa fa-2x fa-meh-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-gamepad"><i class="fa fa-2x fa-gamepad"></i></div>
<div class="col-md-1 sel_ico" value="fa-keyboard-o"><i class="fa fa-2x fa-keyboard-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-flag-o"><i class="fa fa-2x fa-flag-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-flag-checkered"><i class="fa fa-2x fa-flag-checkered"></i></div>
<div class="col-md-1 sel_ico" value="fa-terminal"><i class="fa fa-2x fa-terminal"></i></div>
<div class="col-md-1 sel_ico" value="fa-code"><i class="fa fa-2x fa-code"></i></div>
<div class="col-md-1 sel_ico" value="fa-mail-reply-all"><i class="fa fa-2x fa-mail-reply-all"></i></div>
<div class="col-md-1 sel_ico" value="fa-reply-all"><i class="fa fa-2x fa-reply-all"></i></div>
<div class="col-md-1 sel_ico" value="fa-star-half-empty"><i class="fa fa-2x fa-star-half-empty"></i></div>
<div class="col-md-1 sel_ico" value="fa-star-half-full"><i class="fa fa-2x fa-star-half-full"></i></div>
<div class="col-md-1 sel_ico" value="fa-star-half-o"><i class="fa fa-2x fa-star-half-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-location-arrow"><i class="fa fa-2x fa-location-arrow"></i></div>
<div class="col-md-1 sel_ico" value="fa-crop"><i class="fa fa-2x fa-crop"></i></div>
<div class="col-md-1 sel_ico" value="fa-code-fork"><i class="fa fa-2x fa-code-fork"></i></div>
<div class="col-md-1 sel_ico" value="fa-unlink"><i class="fa fa-2x fa-unlink"></i></div>
<div class="col-md-1 sel_ico" value="fa-chain-broken"><i class="fa fa-2x fa-chain-broken"></i></div>
<div class="col-md-1 sel_ico" value="fa-question"><i class="fa fa-2x fa-question"></i></div>
<div class="col-md-1 sel_ico" value="fa-info"><i class="fa fa-2x fa-info"></i></div>
<div class="col-md-1 sel_ico" value="fa-exclamation"><i class="fa fa-2x fa-exclamation"></i></div>
<div class="col-md-1 sel_ico" value="fa-superscript"><i class="fa fa-2x fa-superscript"></i></div>
<div class="col-md-1 sel_ico" value="fa-subscript"><i class="fa fa-2x fa-subscript"></i></div>
<div class="col-md-1 sel_ico" value="fa-eraser"><i class="fa fa-2x fa-eraser"></i></div>
<div class="col-md-1 sel_ico" value="fa-puzzle-piece"><i class="fa fa-2x fa-puzzle-piece"></i></div>
<div class="col-md-1 sel_ico" value="fa-microphone"><i class="fa fa-2x fa-microphone"></i></div>
<div class="col-md-1 sel_ico" value="fa-microphone-slash"><i class="fa fa-2x fa-microphone-slash"></i></div>
<div class="col-md-1 sel_ico" value="fa-shield"><i class="fa fa-2x fa-shield"></i></div>
<div class="col-md-1 sel_ico" value="fa-calendar-o"><i class="fa fa-2x fa-calendar-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-fire-extinguisher"><i class="fa fa-2x fa-fire-extinguisher"></i></div>
<div class="col-md-1 sel_ico" value="fa-rocket"><i class="fa fa-2x fa-rocket"></i></div>
<div class="col-md-1 sel_ico" value="fa-maxcdn"><i class="fa fa-2x fa-maxcdn"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-circle-left"><i class="fa fa-2x fa-chevron-circle-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-circle-right"><i class="fa fa-2x fa-chevron-circle-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-circle-up"><i class="fa fa-2x fa-chevron-circle-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-chevron-circle-down"><i class="fa fa-2x fa-chevron-circle-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-html5"><i class="fa fa-2x fa-html5"></i></div>
<div class="col-md-1 sel_ico" value="fa-css3"><i class="fa fa-2x fa-css3"></i></div>
<div class="col-md-1 sel_ico" value="fa-anchor"><i class="fa fa-2x fa-anchor"></i></div>
<div class="col-md-1 sel_ico" value="fa-unlock-alt"><i class="fa fa-2x fa-unlock-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-bullseye"><i class="fa fa-2x fa-bullseye"></i></div>
<div class="col-md-1 sel_ico" value="fa-ellipsis-h"><i class="fa fa-2x fa-ellipsis-h"></i></div>
<div class="col-md-1 sel_ico" value="fa-ellipsis-v"><i class="fa fa-2x fa-ellipsis-v"></i></div>
<div class="col-md-1 sel_ico" value="fa-rss-square"><i class="fa fa-2x fa-rss-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-play-circle"><i class="fa fa-2x fa-play-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-ticket"><i class="fa fa-2x fa-ticket"></i></div>
<div class="col-md-1 sel_ico" value="fa-minus-square"><i class="fa fa-2x fa-minus-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-minus-square-o"><i class="fa fa-2x fa-minus-square-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-level-up"><i class="fa fa-2x fa-level-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-level-down"><i class="fa fa-2x fa-level-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-check-square"><i class="fa fa-2x fa-check-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-pencil-square"><i class="fa fa-2x fa-pencil-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-external-link-square"><i class="fa fa-2x fa-external-link-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-share-square"><i class="fa fa-2x fa-share-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-compass"><i class="fa fa-2x fa-compass"></i></div>
<div class="col-md-1 sel_ico" value="fa-toggle-down"><i class="fa fa-2x fa-toggle-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-square-o-down"><i class="fa fa-2x fa-caret-square-o-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-toggle-up"><i class="fa fa-2x fa-toggle-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-square-o-up"><i class="fa fa-2x fa-caret-square-o-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-toggle-right"><i class="fa fa-2x fa-toggle-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-square-o-right"><i class="fa fa-2x fa-caret-square-o-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-euro"><i class="fa fa-2x fa-euro"></i></div>
<div class="col-md-1 sel_ico" value="fa-eur"><i class="fa fa-2x fa-eur"></i></div>
<div class="col-md-1 sel_ico" value="fa-gbp"><i class="fa fa-2x fa-gbp"></i></div>
<div class="col-md-1 sel_ico" value="fa-dollar"><i class="fa fa-2x fa-dollar"></i></div>
<div class="col-md-1 sel_ico" value="fa-usd"><i class="fa fa-2x fa-usd"></i></div>
<div class="col-md-1 sel_ico" value="fa-rupee"><i class="fa fa-2x fa-rupee"></i></div>
<div class="col-md-1 sel_ico" value="fa-inr"><i class="fa fa-2x fa-inr"></i></div>
<div class="col-md-1 sel_ico" value="fa-cny"><i class="fa fa-2x fa-cny"></i></div>
<div class="col-md-1 sel_ico" value="fa-rmb"><i class="fa fa-2x fa-rmb"></i></div>
<div class="col-md-1 sel_ico" value="fa-yen"><i class="fa fa-2x fa-yen"></i></div>
<div class="col-md-1 sel_ico" value="fa-jpy"><i class="fa fa-2x fa-jpy"></i></div>
<div class="col-md-1 sel_ico" value="fa-ruble"><i class="fa fa-2x fa-ruble"></i></div>
<div class="col-md-1 sel_ico" value="fa-rouble"><i class="fa fa-2x fa-rouble"></i></div>
<div class="col-md-1 sel_ico" value="fa-rub"><i class="fa fa-2x fa-rub"></i></div>
<div class="col-md-1 sel_ico" value="fa-won"><i class="fa fa-2x fa-won"></i></div>
<div class="col-md-1 sel_ico" value="fa-krw"><i class="fa fa-2x fa-krw"></i></div>
<div class="col-md-1 sel_ico" value="fa-bitcoin"><i class="fa fa-2x fa-bitcoin"></i></div>
<div class="col-md-1 sel_ico" value="fa-btc"><i class="fa fa-2x fa-btc"></i></div>
<div class="col-md-1 sel_ico" value="fa-file"><i class="fa fa-2x fa-file"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-text"><i class="fa fa-2x fa-file-text"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-alpha-asc"><i class="fa fa-2x fa-sort-alpha-asc"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-alpha-desc"><i class="fa fa-2x fa-sort-alpha-desc"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-amount-asc"><i class="fa fa-2x fa-sort-amount-asc"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-amount-desc"><i class="fa fa-2x fa-sort-amount-desc"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-numeric-asc"><i class="fa fa-2x fa-sort-numeric-asc"></i></div>
<div class="col-md-1 sel_ico" value="fa-sort-numeric-desc"><i class="fa fa-2x fa-sort-numeric-desc"></i></div>
<div class="col-md-1 sel_ico" value="fa-thumbs-up"><i class="fa fa-2x fa-thumbs-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-thumbs-down"><i class="fa fa-2x fa-thumbs-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-youtube-square"><i class="fa fa-2x fa-youtube-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-youtube"><i class="fa fa-2x fa-youtube"></i></div>
<div class="col-md-1 sel_ico" value="fa-xing"><i class="fa fa-2x fa-xing"></i></div>
<div class="col-md-1 sel_ico" value="fa-xing-square"><i class="fa fa-2x fa-xing-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-youtube-play"><i class="fa fa-2x fa-youtube-play"></i></div>
<div class="col-md-1 sel_ico" value="fa-dropbox"><i class="fa fa-2x fa-dropbox"></i></div>
<div class="col-md-1 sel_ico" value="fa-stack-overflow"><i class="fa fa-2x fa-stack-overflow"></i></div>
<div class="col-md-1 sel_ico" value="fa-instagram"><i class="fa fa-2x fa-instagram"></i></div>
<div class="col-md-1 sel_ico" value="fa-flickr"><i class="fa fa-2x fa-flickr"></i></div>
<div class="col-md-1 sel_ico" value="fa-adn"><i class="fa fa-2x fa-adn"></i></div>
<div class="col-md-1 sel_ico" value="fa-bitbucket"><i class="fa fa-2x fa-bitbucket"></i></div>
<div class="col-md-1 sel_ico" value="fa-bitbucket-square"><i class="fa fa-2x fa-bitbucket-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-tumblr"><i class="fa fa-2x fa-tumblr"></i></div>
<div class="col-md-1 sel_ico" value="fa-tumblr-square"><i class="fa fa-2x fa-tumblr-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-long-arrow-down"><i class="fa fa-2x fa-long-arrow-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-long-arrow-up"><i class="fa fa-2x fa-long-arrow-up"></i></div>
<div class="col-md-1 sel_ico" value="fa-long-arrow-left"><i class="fa fa-2x fa-long-arrow-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-long-arrow-right"><i class="fa fa-2x fa-long-arrow-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-apple"><i class="fa fa-2x fa-apple"></i></div>
<div class="col-md-1 sel_ico" value="fa-windows"><i class="fa fa-2x fa-windows"></i></div>
<div class="col-md-1 sel_ico" value="fa-android"><i class="fa fa-2x fa-android"></i></div>
<div class="col-md-1 sel_ico" value="fa-linux"><i class="fa fa-2x fa-linux"></i></div>
<div class="col-md-1 sel_ico" value="fa-dribbble"><i class="fa fa-2x fa-dribbble"></i></div>
<div class="col-md-1 sel_ico" value="fa-skype"><i class="fa fa-2x fa-skype"></i></div>
<div class="col-md-1 sel_ico" value="fa-foursquare"><i class="fa fa-2x fa-foursquare"></i></div>
<div class="col-md-1 sel_ico" value="fa-trello"><i class="fa fa-2x fa-trello"></i></div>
<div class="col-md-1 sel_ico" value="fa-female"><i class="fa fa-2x fa-female"></i></div>
<div class="col-md-1 sel_ico" value="fa-male"><i class="fa fa-2x fa-male"></i></div>
<div class="col-md-1 sel_ico" value="fa-gittip"><i class="fa fa-2x fa-gittip"></i></div>
<div class="col-md-1 sel_ico" value="fa-gratipay"><i class="fa fa-2x fa-gratipay"></i></div>
<div class="col-md-1 sel_ico" value="fa-sun-o"><i class="fa fa-2x fa-sun-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-moon-o"><i class="fa fa-2x fa-moon-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-archive"><i class="fa fa-2x fa-archive"></i></div>
<div class="col-md-1 sel_ico" value="fa-bug"><i class="fa fa-2x fa-bug"></i></div>
<div class="col-md-1 sel_ico" value="fa-vk"><i class="fa fa-2x fa-vk"></i></div>
<div class="col-md-1 sel_ico" value="fa-weibo"><i class="fa fa-2x fa-weibo"></i></div>
<div class="col-md-1 sel_ico" value="fa-renren"><i class="fa fa-2x fa-renren"></i></div>
<div class="col-md-1 sel_ico" value="fa-pagelines"><i class="fa fa-2x fa-pagelines"></i></div>
<div class="col-md-1 sel_ico" value="fa-stack-exchange"><i class="fa fa-2x fa-stack-exchange"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-o-right"><i class="fa fa-2x fa-arrow-circle-o-right"></i></div>
<div class="col-md-1 sel_ico" value="fa-arrow-circle-o-left"><i class="fa fa-2x fa-arrow-circle-o-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-toggle-left"><i class="fa fa-2x fa-toggle-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-caret-square-o-left"><i class="fa fa-2x fa-caret-square-o-left"></i></div>
<div class="col-md-1 sel_ico" value="fa-dot-circle-o"><i class="fa fa-2x fa-dot-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-wheelchair"><i class="fa fa-2x fa-wheelchair"></i></div>
<div class="col-md-1 sel_ico" value="fa-vimeo-square"><i class="fa fa-2x fa-vimeo-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-turkish-lira"><i class="fa fa-2x fa-turkish-lira"></i></div>
<div class="col-md-1 sel_ico" value="fa-try"><i class="fa fa-2x fa-try"></i></div>
<div class="col-md-1 sel_ico" value="fa-plus-square-o"><i class="fa fa-2x fa-plus-square-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-space-shuttle"><i class="fa fa-2x fa-space-shuttle"></i></div>
<div class="col-md-1 sel_ico" value="fa-slack"><i class="fa fa-2x fa-slack"></i></div>
<div class="col-md-1 sel_ico" value="fa-envelope-square"><i class="fa fa-2x fa-envelope-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-wordpress"><i class="fa fa-2x fa-wordpress"></i></div>
<div class="col-md-1 sel_ico" value="fa-openid"><i class="fa fa-2x fa-openid"></i></div>
<div class="col-md-1 sel_ico" value="fa-institution"><i class="fa fa-2x fa-institution"></i></div>
<div class="col-md-1 sel_ico" value="fa-bank"><i class="fa fa-2x fa-bank"></i></div>
<div class="col-md-1 sel_ico" value="fa-university"><i class="fa fa-2x fa-university"></i></div>
<div class="col-md-1 sel_ico" value="fa-mortar-board"><i class="fa fa-2x fa-mortar-board"></i></div>
<div class="col-md-1 sel_ico" value="fa-graduation-cap"><i class="fa fa-2x fa-graduation-cap"></i></div>
<div class="col-md-1 sel_ico" value="fa-yahoo"><i class="fa fa-2x fa-yahoo"></i></div>
<div class="col-md-1 sel_ico" value="fa-google"><i class="fa fa-2x fa-google"></i></div>
<div class="col-md-1 sel_ico" value="fa-reddit"><i class="fa fa-2x fa-reddit"></i></div>
<div class="col-md-1 sel_ico" value="fa-reddit-square"><i class="fa fa-2x fa-reddit-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-stumbleupon-circle"><i class="fa fa-2x fa-stumbleupon-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-stumbleupon"><i class="fa fa-2x fa-stumbleupon"></i></div>
<div class="col-md-1 sel_ico" value="fa-delicious"><i class="fa fa-2x fa-delicious"></i></div>
<div class="col-md-1 sel_ico" value="fa-digg"><i class="fa fa-2x fa-digg"></i></div>
<div class="col-md-1 sel_ico" value="fa-pied-piper-pp"><i class="fa fa-2x fa-pied-piper-pp"></i></div>
<div class="col-md-1 sel_ico" value="fa-pied-piper-alt"><i class="fa fa-2x fa-pied-piper-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-drupal"><i class="fa fa-2x fa-drupal"></i></div>
<div class="col-md-1 sel_ico" value="fa-joomla"><i class="fa fa-2x fa-joomla"></i></div>
<div class="col-md-1 sel_ico" value="fa-language"><i class="fa fa-2x fa-language"></i></div>
<div class="col-md-1 sel_ico" value="fa-fax"><i class="fa fa-2x fa-fax"></i></div>
<div class="col-md-1 sel_ico" value="fa-building"><i class="fa fa-2x fa-building"></i></div>
<div class="col-md-1 sel_ico" value="fa-child"><i class="fa fa-2x fa-child"></i></div>
<div class="col-md-1 sel_ico" value="fa-paw"><i class="fa fa-2x fa-paw"></i></div>
<div class="col-md-1 sel_ico" value="fa-spoon"><i class="fa fa-2x fa-spoon"></i></div>
<div class="col-md-1 sel_ico" value="fa-cube"><i class="fa fa-2x fa-cube"></i></div>
<div class="col-md-1 sel_ico" value="fa-cubes"><i class="fa fa-2x fa-cubes"></i></div>
<div class="col-md-1 sel_ico" value="fa-behance"><i class="fa fa-2x fa-behance"></i></div>
<div class="col-md-1 sel_ico" value="fa-behance-square"><i class="fa fa-2x fa-behance-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-steam"><i class="fa fa-2x fa-steam"></i></div>
<div class="col-md-1 sel_ico" value="fa-steam-square"><i class="fa fa-2x fa-steam-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-recycle"><i class="fa fa-2x fa-recycle"></i></div>
<div class="col-md-1 sel_ico" value="fa-automobile"><i class="fa fa-2x fa-automobile"></i></div>
<div class="col-md-1 sel_ico" value="fa-car"><i class="fa fa-2x fa-car"></i></div>
<div class="col-md-1 sel_ico" value="fa-cab"><i class="fa fa-2x fa-cab"></i></div>
<div class="col-md-1 sel_ico" value="fa-taxi"><i class="fa fa-2x fa-taxi"></i></div>
<div class="col-md-1 sel_ico" value="fa-tree"><i class="fa fa-2x fa-tree"></i></div>
<div class="col-md-1 sel_ico" value="fa-spotify"><i class="fa fa-2x fa-spotify"></i></div>
<div class="col-md-1 sel_ico" value="fa-deviantart"><i class="fa fa-2x fa-deviantart"></i></div>
<div class="col-md-1 sel_ico" value="fa-soundcloud"><i class="fa fa-2x fa-soundcloud"></i></div>
<div class="col-md-1 sel_ico" value="fa-database"><i class="fa fa-2x fa-database"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-pdf-o"><i class="fa fa-2x fa-file-pdf-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-word-o"><i class="fa fa-2x fa-file-word-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-excel-o"><i class="fa fa-2x fa-file-excel-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-powerpoint-o"><i class="fa fa-2x fa-file-powerpoint-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-photo-o"><i class="fa fa-2x fa-file-photo-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-picture-o"><i class="fa fa-2x fa-file-picture-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-image-o"><i class="fa fa-2x fa-file-image-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-zip-o"><i class="fa fa-2x fa-file-zip-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-archive-o"><i class="fa fa-2x fa-file-archive-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-sound-o"><i class="fa fa-2x fa-file-sound-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-audio-o"><i class="fa fa-2x fa-file-audio-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-movie-o"><i class="fa fa-2x fa-file-movie-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-video-o"><i class="fa fa-2x fa-file-video-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-file-code-o"><i class="fa fa-2x fa-file-code-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-vine"><i class="fa fa-2x fa-vine"></i></div>
<div class="col-md-1 sel_ico" value="fa-codepen"><i class="fa fa-2x fa-codepen"></i></div>
<div class="col-md-1 sel_ico" value="fa-jsfiddle"><i class="fa fa-2x fa-jsfiddle"></i></div>
.<div class="col-md-1 sel_ico" value="fa-life-bouy"><i class="fa fa-2x fa-life-bouy"></i></div>
<div class="col-md-1 sel_ico" value="fa-life-buoy"><i class="fa fa-2x fa-life-buoy"></i></div>
<div class="col-md-1 sel_ico" value="fa-life-saver"><i class="fa fa-2x fa-life-saver"></i></div>
<div class="col-md-1 sel_ico" value="fa-support"><i class="fa fa-2x fa-support"></i></div>
<div class="col-md-1 sel_ico" value="fa-life-rin"><i class="fa fa-2x fa-life-rin"></i></div>
<div class="col-md-1 sel_ico" value="fa-circle-o-notch"><i class="fa fa-2x fa-circle-o-notch"></i></div>
<div class="col-md-1 sel_ico" value="fa-ra"><i class="fa fa-2x fa-ra"></i></div>
<div class="col-md-1 sel_ico" value="fa-resistance"><i class="fa fa-2x fa-resistance"></i></div>
<div class="col-md-1 sel_ico" value="fa-rebel"><i class="fa fa-2x fa-rebel"></i></div>
<div class="col-md-1 sel_ico" value="fa-ge"><i class="fa fa-2x fa-ge"></i></div>
<div class="col-md-1 sel_ico" value="fa-empire"><i class="fa fa-2x fa-empire"></i></div>
<div class="col-md-1 sel_ico" value="fa-git-square"><i class="fa fa-2x fa-git-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-git"><i class="fa fa-2x fa-git"></i></div>
<div class="col-md-1 sel_ico" value="fa-y-combinator-square"><i class="fa fa-2x fa-y-combinator-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-yc-square"><i class="fa fa-2x fa-yc-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-hacker-news"><i class="fa fa-2x fa-hacker-news"></i></div>
<div class="col-md-1 sel_ico" value="fa-tencent-weibo"><i class="fa fa-2x fa-tencent-weibo"></i></div>
<div class="col-md-1 sel_ico" value="fa-qq"><i class="fa fa-2x fa-qq"></i></div>
<div class="col-md-1 sel_ico" value="fa-wechat"><i class="fa fa-2x fa-wechat"></i></div>
<div class="col-md-1 sel_ico" value="fa-weixin"><i class="fa fa-2x fa-weixin"></i></div>
<div class="col-md-1 sel_ico" value="fa-send"><i class="fa fa-2x fa-send"></i></div>
<div class="col-md-1 sel_ico" value="fa-paper-plane"><i class="fa fa-2x fa-paper-plane"></i></div>
<div class="col-md-1 sel_ico" value="fa-send-o"><i class="fa fa-2x fa-send-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-paper-plane-o"><i class="fa fa-2x fa-paper-plane-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-history"><i class="fa fa-2x fa-history"></i></div>
<div class="col-md-1 sel_ico" value="fa-circle-thin"><i class="fa fa-2x fa-circle-thin"></i></div>
<div class="col-md-1 sel_ico" value="fa-header"><i class="fa fa-2x fa-header"></i></div>
<div class="col-md-1 sel_ico" value="fa-paragraph"><i class="fa fa-2x fa-paragraph"></i></div>
<div class="col-md-1 sel_ico" value="fa-sliders"><i class="fa fa-2x fa-sliders"></i></div>
<div class="col-md-1 sel_ico" value="fa-share-alt"><i class="fa fa-2x fa-share-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-share-alt-square"><i class="fa fa-2x fa-share-alt-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-bomb"><i class="fa fa-2x fa-bomb"></i></div>
<div class="col-md-1 sel_ico" value="fa-soccer-ball-o"><i class="fa fa-2x fa-soccer-ball-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-futbol-o"><i class="fa fa-2x fa-futbol-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-tty"><i class="fa fa-2x fa-tty"></i></div>
<div class="col-md-1 sel_ico" value="fa-binoculars"><i class="fa fa-2x fa-binoculars"></i></div>
<div class="col-md-1 sel_ico" value="fa-plug"><i class="fa fa-2x fa-plug"></i></div>
<div class="col-md-1 sel_ico" value="fa-slideshare"><i class="fa fa-2x fa-slideshare"></i></div>
<div class="col-md-1 sel_ico" value="fa-twitch"><i class="fa fa-2x fa-twitch"></i></div>
<div class="col-md-1 sel_ico" value="fa-yelp"><i class="fa fa-2x fa-yelp"></i></div>
<div class="col-md-1 sel_ico" value="fa-newspaper-o"><i class="fa fa-2x fa-newspaper-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-wifi"><i class="fa fa-2x fa-wifi"></i></div>
<div class="col-md-1 sel_ico" value="fa-calculator"><i class="fa fa-2x fa-calculator"></i></div>
<div class="col-md-1 sel_ico" value="fa-paypal"><i class="fa fa-2x fa-paypal"></i></div>
<div class="col-md-1 sel_ico" value="fa-google-wallet"><i class="fa fa-2x fa-google-wallet"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-visa"><i class="fa fa-2x fa-cc-visa"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-mastercard"><i class="fa fa-2x fa-cc-mastercard"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-discover"><i class="fa fa-2x fa-cc-discover"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-amex"><i class="fa fa-2x fa-cc-amex"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-paypal"><i class="fa fa-2x fa-cc-paypal"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-stripe"><i class="fa fa-2x fa-cc-stripe"></i></div>
<div class="col-md-1 sel_ico" value="fa-bell-slash"><i class="fa fa-2x fa-bell-slash"></i></div>
<div class="col-md-1 sel_ico" value="fa-bell-slash-o"><i class="fa fa-2x fa-bell-slash-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-trash"><i class="fa fa-2x fa-trash"></i></div>
<div class="col-md-1 sel_ico" value="fa-copyright"><i class="fa fa-2x fa-copyright"></i></div>
<div class="col-md-1 sel_ico" value="fa-at"><i class="fa fa-2x fa-at"></i></div>
<div class="col-md-1 sel_ico" value="fa-eyedropper"><i class="fa fa-2x fa-eyedropper"></i></div>
<div class="col-md-1 sel_ico" value="fa-paint-brush"><i class="fa fa-2x fa-paint-brush"></i></div>
<div class="col-md-1 sel_ico" value="fa-birthday-cake"><i class="fa fa-2x fa-birthday-cake"></i></div>
<div class="col-md-1 sel_ico" value="fa-area-chart"><i class="fa fa-2x fa-area-chart"></i></div>
<div class="col-md-1 sel_ico" value="fa-pie-chart"><i class="fa fa-2x fa-pie-chart"></i></div>
<div class="col-md-1 sel_ico" value="fa-line-chart"><i class="fa fa-2x fa-line-chart"></i></div>
<div class="col-md-1 sel_ico" value="fa-lastfm"><i class="fa fa-2x fa-lastfm"></i></div>
<div class="col-md-1 sel_ico" value="fa-lastfm-square"><i class="fa fa-2x fa-lastfm-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-toggle-off"><i class="fa fa-2x fa-toggle-off"></i></div>
<div class="col-md-1 sel_ico" value="fa-toggle-on"><i class="fa fa-2x fa-toggle-on"></i></div>
<div class="col-md-1 sel_ico" value="fa-bicycle"><i class="fa fa-2x fa-bicycle"></i></div>
<div class="col-md-1 sel_ico" value="fa-bus"><i class="fa fa-2x fa-bus"></i></div>
<div class="col-md-1 sel_ico" value="fa-ioxhost"><i class="fa fa-2x fa-ioxhost"></i></div>
<div class="col-md-1 sel_ico" value="fa-angellist"><i class="fa fa-2x fa-angellist"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc"><i class="fa fa-2x fa-cc"></i></div>
<div class="col-md-1 sel_ico" value="fa-shekel"><i class="fa fa-2x fa-shekel"></i></div>
<div class="col-md-1 sel_ico" value="fa-sheqel"><i class="fa fa-2x fa-sheqel"></i></div>
<div class="col-md-1 sel_ico" value="fa-ils"><i class="fa fa-2x fa-ils"></i></div>
<div class="col-md-1 sel_ico" value="fa-meanpath"><i class="fa fa-2x fa-meanpath"></i></div>
<div class="col-md-1 sel_ico" value="fa-buysellads"><i class="fa fa-2x fa-buysellads"></i></div>
<div class="col-md-1 sel_ico" value="fa-connectdevelop"><i class="fa fa-2x fa-connectdevelop"></i></div>
<div class="col-md-1 sel_ico" value="fa-dashcube"><i class="fa fa-2x fa-dashcube"></i></div>
<div class="col-md-1 sel_ico" value="fa-forumbee"><i class="fa fa-2x fa-forumbee"></i></div>
<div class="col-md-1 sel_ico" value="fa-leanpub"><i class="fa fa-2x fa-leanpub"></i></div>
<div class="col-md-1 sel_ico" value="fa-sellsy"><i class="fa fa-2x fa-sellsy"></i></div>
<div class="col-md-1 sel_ico" value="fa-shirtsinbulk"><i class="fa fa-2x fa-shirtsinbulk"></i></div>
<div class="col-md-1 sel_ico" value="fa-simplybuilt"><i class="fa fa-2x fa-simplybuilt"></i></div>
<div class="col-md-1 sel_ico" value="fa-skyatlas"><i class="fa fa-2x fa-skyatlas"></i></div>
<div class="col-md-1 sel_ico" value="fa-cart-plus"><i class="fa fa-2x fa-cart-plus"></i></div>
<div class="col-md-1 sel_ico" value="fa-cart-arrow-down"><i class="fa fa-2x fa-cart-arrow-down"></i></div>
<div class="col-md-1 sel_ico" value="fa-diamond"><i class="fa fa-2x fa-diamond"></i></div>
<div class="col-md-1 sel_ico" value="fa-ship"><i class="fa fa-2x fa-ship"></i></div>
<div class="col-md-1 sel_ico" value="fa-user-secret"><i class="fa fa-2x fa-user-secret"></i></div>
<div class="col-md-1 sel_ico" value="fa-motorcycle"><i class="fa fa-2x fa-motorcycle"></i></div>
<div class="col-md-1 sel_ico" value="fa-street-view"><i class="fa fa-2x fa-street-view"></i></div>
<div class="col-md-1 sel_ico" value="fa-heartbeat"><i class="fa fa-2x fa-heartbeat"></i></div>
<div class="col-md-1 sel_ico" value="fa-venus"><i class="fa fa-2x fa-venus"></i></div>
<div class="col-md-1 sel_ico" value="fa-mars"><i class="fa fa-2x fa-mars"></i></div>
<div class="col-md-1 sel_ico" value="fa-mercury"><i class="fa fa-2x fa-mercury"></i></div>
<div class="col-md-1 sel_ico" value="fa-intersex"><i class="fa fa-2x fa-intersex"></i></div>
<div class="col-md-1 sel_ico" value="fa-transgender"><i class="fa fa-2x fa-transgender"></i></div>
<div class="col-md-1 sel_ico" value="fa-transgender-alt"><i class="fa fa-2x fa-transgender-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-venus-double"><i class="fa fa-2x fa-venus-double"></i></div>
<div class="col-md-1 sel_ico" value="fa-mars-double"><i class="fa fa-2x fa-mars-double"></i></div>
<div class="col-md-1 sel_ico" value="fa-venus-mars"><i class="fa fa-2x fa-venus-mars"></i></div>
<div class="col-md-1 sel_ico" value="fa-mars-stroke"><i class="fa fa-2x fa-mars-stroke"></i></div>
<div class="col-md-1 sel_ico" value="fa-mars-stroke-v"><i class="fa fa-2x fa-mars-stroke-v"></i></div>
<div class="col-md-1 sel_ico" value="fa-mars-stroke-h"><i class="fa fa-2x fa-mars-stroke-h"></i></div>
<div class="col-md-1 sel_ico" value="fa-neuter"><i class="fa fa-2x fa-neuter"></i></div>
<div class="col-md-1 sel_ico" value="fa-genderless"><i class="fa fa-2x fa-genderless"></i></div>
<div class="col-md-1 sel_ico" value="fa-facebook-official"><i class="fa fa-2x fa-facebook-official"></i></div>
<div class="col-md-1 sel_ico" value="fa-pinterest-p"><i class="fa fa-2x fa-pinterest-p"></i></div>
<div class="col-md-1 sel_ico" value="fa-whatsapp"><i class="fa fa-2x fa-whatsapp"></i></div>
<div class="col-md-1 sel_ico" value="fa-server"><i class="fa fa-2x fa-server"></i></div>
<div class="col-md-1 sel_ico" value="fa-user-plus"><i class="fa fa-2x fa-user-plus"></i></div>
<div class="col-md-1 sel_ico" value="fa-user-times"><i class="fa fa-2x fa-user-times"></i></div>
<div class="col-md-1 sel_ico" value="fa-hotel"><i class="fa fa-2x fa-hotel"></i></div>
<div class="col-md-1 sel_ico" value="fa-bed"><i class="fa fa-2x fa-bed"></i></div>
<div class="col-md-1 sel_ico" value="fa-viacoin"><i class="fa fa-2x fa-viacoin"></i></div>
<div class="col-md-1 sel_ico" value="fa-train"><i class="fa fa-2x fa-train"></i></div>
<div class="col-md-1 sel_ico" value="fa-subway"><i class="fa fa-2x fa-subway"></i></div>
<div class="col-md-1 sel_ico" value="fa-medium"><i class="fa fa-2x fa-medium"></i></div>
<div class="col-md-1 sel_ico" value="fa-yc"><i class="fa fa-2x fa-yc"></i></div>
<div class="col-md-1 sel_ico" value="fa-y-combinator"><i class="fa fa-2x fa-y-combinator"></i></div>
<div class="col-md-1 sel_ico" value="fa-optin-monster"><i class="fa fa-2x fa-optin-monster"></i></div>
<div class="col-md-1 sel_ico" value="fa-opencart"><i class="fa fa-2x fa-opencart"></i></div>
<div class="col-md-1 sel_ico" value="fa-expeditedssl"><i class="fa fa-2x fa-expeditedssl"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-4"><i class="fa fa-2x fa-battery-4"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery"><i class="fa fa-2x fa-battery"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-full"><i class="fa fa-2x fa-battery-full"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-3"><i class="fa fa-2x fa-battery-3"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-three-quarters"><i class="fa fa-2x fa-battery-three-quarters"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-2"><i class="fa fa-2x fa-battery-2"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-half"><i class="fa fa-2x fa-battery-half"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-1"><i class="fa fa-2x fa-battery-1"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-quarter"><i class="fa fa-2x fa-battery-quarter"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-0"><i class="fa fa-2x fa-battery-0"></i></div>
<div class="col-md-1 sel_ico" value="fa-battery-empty"><i class="fa fa-2x fa-battery-empty"></i></div>
<div class="col-md-1 sel_ico" value="fa-mouse-pointer"><i class="fa fa-2x fa-mouse-pointer"></i></div>
<div class="col-md-1 sel_ico" value="fa-i-cursor"><i class="fa fa-2x fa-i-cursor"></i></div>
<div class="col-md-1 sel_ico" value="fa-object-group"><i class="fa fa-2x fa-object-group"></i></div>
<div class="col-md-1 sel_ico" value="fa-object-ungroup"><i class="fa fa-2x fa-object-ungroup"></i></div>
<div class="col-md-1 sel_ico" value="fa-sticky-note"><i class="fa fa-2x fa-sticky-note"></i></div>
<div class="col-md-1 sel_ico" value="fa-sticky-note-o"><i class="fa fa-2x fa-sticky-note-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-jcb"><i class="fa fa-2x fa-cc-jcb"></i></div>
<div class="col-md-1 sel_ico" value="fa-cc-diners-club"><i class="fa fa-2x fa-cc-diners-club"></i></div>
<div class="col-md-1 sel_ico" value="fa-clone"><i class="fa fa-2x fa-clone"></i></div>
<div class="col-md-1 sel_ico" value="fa-balance-scale"><i class="fa fa-2x fa-balance-scale"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass-o"><i class="fa fa-2x fa-hourglass-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass-1"><i class="fa fa-2x fa-hourglass-1"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass-start"><i class="fa fa-2x fa-hourglass-start"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass-2"><i class="fa fa-2x fa-hourglass-2"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass-half"><i class="fa fa-2x fa-hourglass-half"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass-3"><i class="fa fa-2x fa-hourglass-3"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass-end"><i class="fa fa-2x fa-hourglass-end"></i></div>
<div class="col-md-1 sel_ico" value="fa-hourglass"><i class="fa fa-2x fa-hourglass"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-grab-o"><i class="fa fa-2x fa-hand-grab-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-rock-o"><i class="fa fa-2x fa-hand-rock-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-stop-o"><i class="fa fa-2x fa-hand-stop-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-paper-o"><i class="fa fa-2x fa-hand-paper-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-scissors-o"><i class="fa fa-2x fa-hand-scissors-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-lizard-o"><i class="fa fa-2x fa-hand-lizard-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-spock-o"><i class="fa fa-2x fa-hand-spock-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-pointer-o"><i class="fa fa-2x fa-hand-pointer-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-hand-peace-o"><i class="fa fa-2x fa-hand-peace-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-trademark"><i class="fa fa-2x fa-trademark"></i></div>
<div class="col-md-1 sel_ico" value="fa-registered"><i class="fa fa-2x fa-registered"></i></div>
<div class="col-md-1 sel_ico" value="fa-creative-commons"><i class="fa fa-2x fa-creative-commons"></i></div>
<div class="col-md-1 sel_ico" value="fa-gg"><i class="fa fa-2x fa-gg"></i></div>
<div class="col-md-1 sel_ico" value="fa-gg-circle"><i class="fa fa-2x fa-gg-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-tripadvisor"><i class="fa fa-2x fa-tripadvisor"></i></div>
<div class="col-md-1 sel_ico" value="fa-odnoklassniki"><i class="fa fa-2x fa-odnoklassniki"></i></div>
<div class="col-md-1 sel_ico" value="fa-odnoklassniki-square"><i class="fa fa-2x fa-odnoklassniki-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-get-pocket"><i class="fa fa-2x fa-get-pocket"></i></div>
<div class="col-md-1 sel_ico" value="fa-wikipedia-w"><i class="fa fa-2x fa-wikipedia-w"></i></div>
<div class="col-md-1 sel_ico" value="fa-safari"><i class="fa fa-2x fa-safari"></i></div>
<div class="col-md-1 sel_ico" value="fa-chrome"><i class="fa fa-2x fa-chrome"></i></div>
<div class="col-md-1 sel_ico" value="fa-firefox"><i class="fa fa-2x fa-firefox"></i></div>
<div class="col-md-1 sel_ico" value="fa-opera"><i class="fa fa-2x fa-opera"></i></div>
<div class="col-md-1 sel_ico" value="fa-internet-explorer"><i class="fa fa-2x fa-internet-explorer"></i></div>
<div class="col-md-1 sel_ico" value="fa-tv"><i class="fa fa-2x fa-tv"></i></div>
<div class="col-md-1 sel_ico" value="fa-television"><i class="fa fa-2x fa-television"></i></div>
<div class="col-md-1 sel_ico" value="fa-contao"><i class="fa fa-2x fa-contao"></i></div>
<div class="col-md-1 sel_ico" value="fa-500px"><i class="fa fa-2x fa-500px"></i></div>
<div class="col-md-1 sel_ico" value="fa-amazon"><i class="fa fa-2x fa-amazon"></i></div>
<div class="col-md-1 sel_ico" value="fa-calendar-plus-o"><i class="fa fa-2x fa-calendar-plus-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-calendar-minus-o"><i class="fa fa-2x fa-calendar-minus-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-calendar-times-o"><i class="fa fa-2x fa-calendar-times-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-calendar-check-o"><i class="fa fa-2x fa-calendar-check-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-industry"><i class="fa fa-2x fa-industry"></i></div>
<div class="col-md-1 sel_ico" value="fa-map-pin"><i class="fa fa-2x fa-map-pin"></i></div>
<div class="col-md-1 sel_ico" value="fa-map-signs"><i class="fa fa-2x fa-map-signs"></i></div>
<div class="col-md-1 sel_ico" value="fa-map-o"><i class="fa fa-2x fa-map-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-map"><i class="fa fa-2x fa-map"></i></div>
<div class="col-md-1 sel_ico" value="fa-commenting"><i class="fa fa-2x fa-commenting"></i></div>
<div class="col-md-1 sel_ico" value="fa-commenting-o"><i class="fa fa-2x fa-commenting-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-houzz"><i class="fa fa-2x fa-houzz"></i></div>
<div class="col-md-1 sel_ico" value="fa-vimeo"><i class="fa fa-2x fa-vimeo"></i></div>
<div class="col-md-1 sel_ico" value="fa-black-tie"><i class="fa fa-2x fa-black-tie"></i></div>
<div class="col-md-1 sel_ico" value="fa-fonticons"><i class="fa fa-2x fa-fonticons"></i></div>
<div class="col-md-1 sel_ico" value="fa-reddit-alien"><i class="fa fa-2x fa-reddit-alien"></i></div>
<div class="col-md-1 sel_ico" value="fa-edge"><i class="fa fa-2x fa-edge"></i></div>
<div class="col-md-1 sel_ico" value="fa-credit-card-alt"><i class="fa fa-2x fa-credit-card-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-codiepie"><i class="fa fa-2x fa-codiepie"></i></div>
<div class="col-md-1 sel_ico" value="fa-modx"><i class="fa fa-2x fa-modx"></i></div>
<div class="col-md-1 sel_ico" value="fa-fort-awesome"><i class="fa fa-2x fa-fort-awesome"></i></div>
<div class="col-md-1 sel_ico" value="fa-usb"><i class="fa fa-2x fa-usb"></i></div>
<div class="col-md-1 sel_ico" value="fa-product-hunt"><i class="fa fa-2x fa-product-hunt"></i></div>
<div class="col-md-1 sel_ico" value="fa-mixcloud"><i class="fa fa-2x fa-mixcloud"></i></div>
<div class="col-md-1 sel_ico" value="fa-scribd"><i class="fa fa-2x fa-scribd"></i></div>
<div class="col-md-1 sel_ico" value="fa-pause-circle"><i class="fa fa-2x fa-pause-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-pause-circle-o"><i class="fa fa-2x fa-pause-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-stop-circle"><i class="fa fa-2x fa-stop-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-stop-circle-o"><i class="fa fa-2x fa-stop-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-shopping-bag"><i class="fa fa-2x fa-shopping-bag"></i></div>
<div class="col-md-1 sel_ico" value="fa-shopping-basket"><i class="fa fa-2x fa-shopping-basket"></i></div>
<div class="col-md-1 sel_ico" value="fa-hashtag"><i class="fa fa-2x fa-hashtag"></i></div>
<div class="col-md-1 sel_ico" value="fa-bluetooth"><i class="fa fa-2x fa-bluetooth"></i></div>
<div class="col-md-1 sel_ico" value="fa-bluetooth-b"><i class="fa fa-2x fa-bluetooth-b"></i></div>
<div class="col-md-1 sel_ico" value="fa-percent"><i class="fa fa-2x fa-percent"></i></div>
<div class="col-md-1 sel_ico" value="fa-gitlab"><i class="fa fa-2x fa-gitlab"></i></div>
<div class="col-md-1 sel_ico" value="fa-wpbeginner"><i class="fa fa-2x fa-wpbeginner"></i></div>
<div class="col-md-1 sel_ico" value="fa-wpforms"><i class="fa fa-2x fa-wpforms"></i></div>
<div class="col-md-1 sel_ico" value="fa-envira"><i class="fa fa-2x fa-envira"></i></div>
<div class="col-md-1 sel_ico" value="fa-universal-access"><i class="fa fa-2x fa-universal-access"></i></div>
<div class="col-md-1 sel_ico" value="fa-wheelchair-alt"><i class="fa fa-2x fa-wheelchair-alt"></i></div>
<div class="col-md-1 sel_ico" value="fa-question-circle-o"><i class="fa fa-2x fa-question-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-blind"><i class="fa fa-2x fa-blind"></i></div>
<div class="col-md-1 sel_ico" value="fa-audio-description"><i class="fa fa-2x fa-audio-description"></i></div>
<div class="col-md-1 sel_ico" value="fa-volume-control-phone"><i class="fa fa-2x fa-volume-control-phone"></i></div>
<div class="col-md-1 sel_ico" value="fa-braille"><i class="fa fa-2x fa-braille"></i></div>
<div class="col-md-1 sel_ico" value="fa-assistive-listening-systems"><i class="fa fa-2x fa-assistive-listening-systems"></i></div>
<div class="col-md-1 sel_ico" value="fa-asl-interpreting"><i class="fa fa-2x fa-asl-interpreting"></i></div>
<div class="col-md-1 sel_ico" value="fa-american-sign-language-interpreting"><i class="fa fa-2x fa-american-sign-language-interpreting"></i></div>
<div class="col-md-1 sel_ico" value="fa-deafness"><i class="fa fa-2x fa-deafness"></i></div>
<div class="col-md-1 sel_ico" value="fa-hard-of-hearing"><i class="fa fa-2x fa-hard-of-hearing"></i></div>
<div class="col-md-1 sel_ico" value="fa-deaf"><i class="fa fa-2x fa-deaf"></i></div>
<div class="col-md-1 sel_ico" value="fa-glide"><i class="fa fa-2x fa-glide"></i></div>
<div class="col-md-1 sel_ico" value="fa-glide-g"><i class="fa fa-2x fa-glide-g"></i></div>
<div class="col-md-1 sel_ico" value="fa-signing"><i class="fa fa-2x fa-signing"></i></div>
<div class="col-md-1 sel_ico" value="fa-sign-language"><i class="fa fa-2x fa-sign-language"></i></div>
<div class="col-md-1 sel_ico" value="fa-low-vision"><i class="fa fa-2x fa-low-vision"></i></div>
<div class="col-md-1 sel_ico" value="fa-viadeo"><i class="fa fa-2x fa-viadeo"></i></div>
<div class="col-md-1 sel_ico" value="fa-viadeo-square"><i class="fa fa-2x fa-viadeo-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-snapchat"><i class="fa fa-2x fa-snapchat"></i></div>
<div class="col-md-1 sel_ico" value="fa-snapchat-ghost"><i class="fa fa-2x fa-snapchat-ghost"></i></div>
<div class="col-md-1 sel_ico" value="fa-snapchat-square"><i class="fa fa-2x fa-snapchat-square"></i></div>
<div class="col-md-1 sel_ico" value="fa-pied-piper"><i class="fa fa-2x fa-pied-piper"></i></div>
<div class="col-md-1 sel_ico" value="fa-first-order"><i class="fa fa-2x fa-first-order"></i></div>
<div class="col-md-1 sel_ico" value="fa-yoast"><i class="fa fa-2x fa-yoast"></i></div>
<div class="col-md-1 sel_ico" value="fa-themeisle"><i class="fa fa-2x fa-themeisle"></i></div>
<div class="col-md-1 sel_ico" value="fa-google-plus-circle"><i class="fa fa-2x fa-google-plus-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-google-plus-official"><i class="fa fa-2x fa-google-plus-official"></i></div>
<div class="col-md-1 sel_ico" value="fa-fa"><i class="fa fa-2x fa-fa"></i></div>
<div class="col-md-1 sel_ico" value="fa-font-awesome"><i class="fa fa-2x fa-font-awesome"></i></div>
<div class="col-md-1 sel_ico" value="fa-handshake-o"><i class="fa fa-2x fa-handshake-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-envelope-open"><i class="fa fa-2x fa-envelope-open"></i></div>
<div class="col-md-1 sel_ico" value="fa-envelope-open-o"><i class="fa fa-2x fa-envelope-open-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-linode"><i class="fa fa-2x fa-linode"></i></div>
<div class="col-md-1 sel_ico" value="fa-address-book"><i class="fa fa-2x fa-address-book"></i></div>
<div class="col-md-1 sel_ico" value="fa-address-book-o"><i class="fa fa-2x fa-address-book-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-vcard"><i class="fa fa-2x fa-vcard"></i></div>
<div class="col-md-1 sel_ico" value="fa-address-card"><i class="fa fa-2x fa-address-card"></i></div>
<div class="col-md-1 sel_ico" value="fa-vcard-o"><i class="fa fa-2x fa-vcard-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-address-card-o"><i class="fa fa-2x fa-address-card-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-user-circle"><i class="fa fa-2x fa-user-circle"></i></div>
<div class="col-md-1 sel_ico" value="fa-user-circle-o"><i class="fa fa-2x fa-user-circle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-user-o"><i class="fa fa-2x fa-user-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-id-badge"><i class="fa fa-2x fa-id-badge"></i></div>
<div class="col-md-1 sel_ico" value="fa-drivers-license"><i class="fa fa-2x fa-drivers-license"></i></div>
<div class="col-md-1 sel_ico" value="fa-id-card"><i class="fa fa-2x fa-id-card"></i></div>
<div class="col-md-1 sel_ico" value="fa-drivers-license-o"><i class="fa fa-2x fa-drivers-license-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-id-card-o"><i class="fa fa-2x fa-id-card-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-quora"><i class="fa fa-2x fa-quora"></i></div>
<div class="col-md-1 sel_ico" value="fa-free-code-camp"><i class="fa fa-2x fa-free-code-camp"></i></div>
<div class="col-md-1 sel_ico" value="fa-telegram"><i class="fa fa-2x fa-telegram"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-4"><i class="fa fa-2x fa-thermometer-4"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer"><i class="fa fa-2x fa-thermometer"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-full"><i class="fa fa-2x fa-thermometer-full"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-3"><i class="fa fa-2x fa-thermometer-3"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-three-quarters"><i class="fa fa-2x fa-thermometer-three-quarters"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-2"><i class="fa fa-2x fa-thermometer-2"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-half"><i class="fa fa-2x fa-thermometer-half"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-1"><i class="fa fa-2x fa-thermometer-1"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-quarter"><i class="fa fa-2x fa-thermometer-quarter"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-0"><i class="fa fa-2x fa-thermometer-0"></i></div>
<div class="col-md-1 sel_ico" value="fa-thermometer-empty"><i class="fa fa-2x fa-thermometer-empty"></i></div>
<div class="col-md-1 sel_ico" value="fa-shower"><i class="fa fa-2x fa-shower"></i></div>
<div class="col-md-1 sel_ico" value="fa-bathtub"><i class="fa fa-2x fa-bathtub"></i></div>
<div class="col-md-1 sel_ico" value="fa-s15"><i class="fa fa-2x fa-s15"></i></div>
<div class="col-md-1 sel_ico" value="fa-bath"><i class="fa fa-2x fa-bath"></i></div>
<div class="col-md-1 sel_ico" value="fa-podcast"><i class="fa fa-2x fa-podcast"></i></div>
<div class="col-md-1 sel_ico" value="fa-window-maximize"><i class="fa fa-2x fa-window-maximize"></i></div>
<div class="col-md-1 sel_ico" value="fa-window-minimize"><i class="fa fa-2x fa-window-minimize"></i></div>
<div class="col-md-1 sel_ico" value="fa-window-restore"><i class="fa fa-2x fa-window-restore"></i></div>
<div class="col-md-1 sel_ico" value="fa-times-rectangle"><i class="fa fa-2x fa-times-rectangle"></i></div>
<div class="col-md-1 sel_ico" value="fa-window-close"><i class="fa fa-2x fa-window-close"></i></div>
<div class="col-md-1 sel_ico" value="fa-times-rectangle-o"><i class="fa fa-2x fa-times-rectangle-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-window-close-o"><i class="fa fa-2x fa-window-close-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-bandcamp"><i class="fa fa-2x fa-bandcamp"></i></div>
<div class="col-md-1 sel_ico" value="fa-grav"><i class="fa fa-2x fa-grav"></i></div>
<div class="col-md-1 sel_ico" value="fa-etsy"><i class="fa fa-2x fa-etsy"></i></div>
<div class="col-md-1 sel_ico" value="fa-imdb"><i class="fa fa-2x fa-imdb"></i></div>
<div class="col-md-1 sel_ico" value="fa-ravelry"><i class="fa fa-2x fa-ravelry"></i></div>
<div class="col-md-1 sel_ico" value="fa-eercast"><i class="fa fa-2x fa-eercast"></i></div>
<div class="col-md-1 sel_ico" value="fa-microchip"><i class="fa fa-2x fa-microchip"></i></div>
<div class="col-md-1 sel_ico" value="fa-snowflake-o"><i class="fa fa-2x fa-snowflake-o"></i></div>
<div class="col-md-1 sel_ico" value="fa-superpowers"><i class="fa fa-2x fa-superpowers"></i></div>
<div class="col-md-1 sel_ico" value="fa-wpexplorer"><i class="fa fa-2x fa-wpexplorer"></i></div>
<div class="col-md-1 sel_ico" value="fa-meetup"><i class="fa fa-2x fa-meetup"></i></div>
</div>